import uuid
from typing import List, Dict, Any, Optional

class ExecutionPlan:
    """
    Represents a multi-step execution plan generated by the Planning Engine.
    Tracks step sequences, expected files, execution times, and errors.
    """
    def __init__(
        self,
        query: str,
        intent: str,
        steps: List[str],
        required_artifacts: List[str],
        expected_outputs: List[str]
    ):
        self.plan_id = f"plan_{str(uuid.uuid4())[:8]}"
        self.query = query
        self.intent = intent
        self.steps = steps
        self.required_artifacts = required_artifacts
        self.expected_outputs = expected_outputs
        self.status = "pending"
        self.execution_time = 0.0
        self.errors = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert the ExecutionPlan state to a dictionary representation."""
        return {
            "plan_id": self.plan_id,
            "query": self.query,
            "intent": self.intent,
            "steps": self.steps,
            "required_artifacts": self.required_artifacts,
            "expected_outputs": self.expected_outputs,
            "status": self.status,
            "execution_time": f"{self.execution_time:.2f} seconds",
            "errors": self.errors
        }
